server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: battleship
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

battleship:
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:5173}
